// client/src/app/app.component.ts
import { Component } from '@angular/core';
import { ReportsService } from './core/services/reports.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'client';

  constructor(private reports: ReportsService) {
    this.reports.getClassRegistrationReports().subscribe(val => console.log(val))
  }
}

<div class="mt-24 max-w-screen-md mx-auto px-2">
  <h1 class="text-4xl font-display mb-8">Reports</h1>
  <app-class-registration-reports class="w-full"/>
</div>

// react-client/src/components/App.tsx
import React from 'react';
import ClassRegistrationReport from './class-registration-report/ClassRegistrationReport';

export default function App() {
  return (
    <div className="mt-24 max-w-screen-md mx-auto px-2">
      <h1 className="text-4xl font-display mb-4">Reports</h1>
      <ClassRegistrationReport />
    </div>
  );
}
